name: Go test

on:
  pull_request:
    branches:
      - main

  push:
    paths:
      - .github/workflows/go-test.yml
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.18.*'
          - '1.19.*'
          - '1.20.*'
          - '1.21.*'
          - '1.22.*'

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # 5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        working-directory: src
        run: go get -v .

      - name: Test with the Go CLI
        working-directory: src
        run: go test
