name: Go test

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

  push:
    paths:
      - .github/workflows/go-test.yml
      - src/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.18.*'
          - '1.19.*'
          - '1.20.*'
          - '1.21.*'
          - '1.22.*'
          - '1.23.*'

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # 4.1.1

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # 5.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        working-directory: src
        run: go get -v .

      - name: Test with the Go CLI
        working-directory: src
        run: go test
